version: "3.9"
services:
  sociopedia-frontend:
    image: hims0301/frontend:latest
    container_name: sociopedia-frontend
    # Keep stdin_open because we don't want this container to exit immediately which it
    # otherwise would have because there's no foreground processes
    stdin_open: true
    # ports:
    #   - "6002:6002"
    network_mode: host
     # - sociopedia
      #sociopedia:
       # ipv4_address: 172.28.1.6

  sociopedia-backend:
    image: hims0301/backend:latest
    container_name: sociopedia-backend
    ports:
      - "3001:3001"
    networks:
      - sociopedia
      #sociopedia:
      #  ipv4_address: 172.28.1.7
    # Using Docker volume for persisting logs
    # ./backend/logs refers to the path /home/backend/logs on the host machine
    # and we're linking it to logs folder on the container machine where Morgan logger logs its output
    #volumes:
    #  - ./backend/logs:/app/logs/
    volumes:
      - /home/himanshu/Downloads/socialLogs:/usr/src/app/logs/


  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
   # volumes:
    #- elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - sociopedia

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - /home/himanshu/Downloads/socialLogs/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
      - Elasticsearch
    ports:
    - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - sociopedia

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch  
    networks:
      - sociopedia

networks:
  sociopedia:
    ipam:
      driver: default
      config:
      - subnet: 127.0.0.1/8