name: Build and Deploy

# Run the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - master

# Set environment variables
env:
  MONGODB_URL: ${{ secrets.MONGODB_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PORT: 3001
# This is the workflow that is being run.
jobs:
  build:
    # This is telling GitHub to run the workflow on the latest version of Ubuntu.
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and run tests for the client application
      - name: Install and Test Client
        working-directory: ./SocialFrontEnd/socialfrontend
        run: |
          npm install

      # Install dependencies, export environment variables to be used by application and run tests for the server application
      - name: Install and Test Server
        working-directory: ./SocialBackend
        run: |
          npm install
          export MONGODB_URI=$MONGODB_URL
          export TOKEN_KEY=$JWT_SECRET
          export PORT=$PORT
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Build a Docker image for the client application
      - name: Build Client Docker Image
        working-directory: ./SocialFrontEnd/socialfrontend
        # Build image with tag rakeshpotnuru/productivity-app:client
        run: |
          docker build -t himanshudigrase/socialmedia:frontend-${{github.run_number}} .

      # Build a Docker image for the server application
      - name: Build Server Docker Image
        working-directory:
          ./SocialBackend
          # Build image with tag rakeshpotnuru/productivity-app:server
        run: |
          docker build -t himanshudigrase/socialmedia:backend-${{github.run_number}} .

      # Login to Docker Hub using credentials from repository secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push himanshudigrase/socialMedia:frontEnd-${{github.run_number}}
          docker push himanshudigrase/socialMedia:backEnd-${{github.run_number}}
